name: bridge_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.2.6 <4.0.0"

dependencies:
    auto_size_text: ^3.0.0
    flutter:
        sdk: flutter
    geolocator: ^11.0.0
    http: ^0.13.3
    just_audio: ^0.9.36
    path_provider: ^2.1.2
    record: ^5.0.4
    shared_preferences: ^2.2.2
    speech_to_text: ^6.6.0
    uuid: ^4.3.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    fonts:
        - family: Pretendard
          fonts:
              - asset: assets/fonts/Pretendard-Black.otf
                weight: 900
              - asset: assets/fonts/Pretendard-Bold.otf
                weight: 700
              - asset: assets/fonts/Pretendard-ExtraBold.otf
                weight: 800
              - asset: assets/fonts/Pretendard-ExtraLight.otf
                weight: 200
              - asset: assets/fonts/Pretendard-Light.otf
                weight: 300
              - asset: assets/fonts/Pretendard-Medium.otf
                weight: 500
              - asset: assets/fonts/Pretendard-Regular.otf
                weight: 400
              - asset: assets/fonts/Pretendard-SemiBold.otf
                weight: 600
              - asset: assets/fonts/Pretendard-Thin.otf
                weight: 100
